# Generated by Django 3.2.3 on 2024-09-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to='users/'),
        ),
    ]
