# Generated by Django 3.2.3 on 2024-09-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite',
            field=models.ManyToManyField(related_name='favorites', to='recipes.Recipe'),
        ),
    ]
