# Generated by Django 3.2.3 on 2024-09-17 07:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
        ('users', '0002_customuser_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='recipes.Recipe'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='followers', through='users.Follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
