# Generated by Django 3.2.3 on 2024-09-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
        ('users', '0003_auto_20240917_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='shopping_cart',
            field=models.ManyToManyField(blank=True, related_name='shopping', to='recipes.Recipe'),
        ),
    ]
