# Generated by Django 3.2.3 on 2024-09-17 07:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
        ('users', '0004_customuser_shopping_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='users/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='recipes.Recipe', verbose_name='Избранное'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='shopping_cart',
            field=models.ManyToManyField(blank=True, related_name='shopping', to='recipes.Recipe', verbose_name='Список покупок'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='followers', through='users.Follow', to=settings.AUTH_USER_MODEL, verbose_name='Подписки'),
        ),
    ]
